In [25]:
from tensorflow.keras.preprocessing.text import one_hot

In [26]:
## Sentences
sent= [ 'the glass of milk',
       'the glass of juice',
       'the cup of tea',
       ' I am a good boy',
       'I am s good developer',
       'Understand the meaning of words',
       'Your videos are good',

]

In [27]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 ' I am a good boy',
 'I am s good developer',
 'Understand the meaning of words',
 'Your videos are good']

In [28]:
## Define the vocabulary size
voc_size=10000

In [29]:
## One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7815, 1608, 2114, 3623],
 [7815, 1608, 2114, 8411],
 [7815, 466, 2114, 9425],
 [1369, 6798, 7252, 5211, 4595],
 [1369, 6798, 8979, 5211, 6685],
 [5673, 7815, 3168, 2114, 6455],
 [4835, 8126, 9192, 5211]]

In [30]:
## word Enbedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [31]:
import numpy as np

In [32]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7815 1608 2114 3623]
 [   0    0    0    0 7815 1608 2114 8411]
 [   0    0    0    0 7815  466 2114 9425]
 [   0    0    0 1369 6798 7252 5211 4595]
 [   0    0    0 1369 6798 8979 5211 6685]
 [   0    0    0 5673 7815 3168 2114 6455]
 [   0    0    0    0 4835 8126 9192 5211]]


In [33]:
## feature representation
dim=10

In [34]:
model=Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_shape=(sent_length,)))
model.compile('adam','mse')

e:\Deep Learning NLP\venv\Lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [35]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [36]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[[-0.03031613,  0.01290399,  0.00520868, -0.00371233,
         -0.01556062,  0.02240738, -0.04228801,  0.0255437 ,
         -0.02228801, -0.04302   ],
        [-0.03031613,  0.01290399,  0.00520868, -0.00371233,
         -0.01556062,  0.02240738, -0.04228801,  0.0255437 ,
         -0.02228801, -0.04302   ],
        [-0.03031613,  0.01290399,  0.00520868, -0.00371233,
         -0.01556062,  0.02240738, -0.04228801,  0.0255437 ,
         -0.02228801, -0.04302   ],
        [-0.03031613,  0.01290399,  0.00520868, -0.00371233,
         -0.01556062,  0.02240738, -0.04228801,  0.0255437 ,
         -0.02228801, -0.04302   ],
        [ 0.01664729,  0.01466751, -0.01278521, -0.03188521,
         -0.03833453,  0.00239631, -0.03652189,  0.02364895,
         -0.00620904,  0.03592527],
        [ 0.03131467,  0.01178702, -0.03434758,  0.01473243,
         -0.03533769, -0.0123669 ,  0.01877834, -0.04212205,
         -0.02996441,  0.00827367],
        [-0.00850159, -0.01066772,  0.00895163,  0.0

In [37]:
embedded_docs[0]

array([   0,    0,    0,    0, 7815, 1608, 2114, 3623], dtype=int32)

In [40]:
model.predict(np.expand_dims(embedded_docs[0],axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


array([[[-0.03031613,  0.01290399,  0.00520868, -0.00371233,
         -0.01556062,  0.02240738, -0.04228801,  0.0255437 ,
         -0.02228801, -0.04302   ],
        [-0.03031613,  0.01290399,  0.00520868, -0.00371233,
         -0.01556062,  0.02240738, -0.04228801,  0.0255437 ,
         -0.02228801, -0.04302   ],
        [-0.03031613,  0.01290399,  0.00520868, -0.00371233,
         -0.01556062,  0.02240738, -0.04228801,  0.0255437 ,
         -0.02228801, -0.04302   ],
        [-0.03031613,  0.01290399,  0.00520868, -0.00371233,
         -0.01556062,  0.02240738, -0.04228801,  0.0255437 ,
         -0.02228801, -0.04302   ],
        [ 0.01664729,  0.01466751, -0.01278521, -0.03188521,
         -0.03833453,  0.00239631, -0.03652189,  0.02364895,
         -0.00620904,  0.03592527],
        [ 0.03131467,  0.01178702, -0.03434758,  0.01473243,
         -0.03533769, -0.0123669 ,  0.01877834, -0.04212205,
         -0.02996441,  0.00827367],
        [-0.00850159, -0.01066772,  0.00895163,  0.0